development:
 adapter: mysql
 encoding: utf8
 database: roomstore_development
 username: root
 password: 123
 host: localhost

test:
 adapter: mysql
 encoding: utf8
 database: roomstore_test
 username: root
 password: 123
 host: localhost

production:
 adapter: mysql
 encoding: utf8
 database: roomstore_production
 username: root
 password: 123
 host: localhost

